# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AndroidSystemControlMessage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AndroidSystemControlMessage.proto',
  package='android.vts',
  serialized_pb='\n!AndroidSystemControlMessage.proto\x12\x0b\x61ndroid.vts\"j\n\"AndroidSystemControlCommandMessage\x12.\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x18.android.vts.CommandType\x12\x14\n\x0btarget_name\x18\xe9\x07 \x01(\x0c\"h\n#AndroidSystemControlResponseMessage\x12\x30\n\rresponse_code\x18\x01 \x01(\x0e\x32\x19.android.vts.ResponseCode\x12\x0f\n\x06reason\x18\xe9\x07 \x01(\x0c*\xa7\x01\n\x0b\x43ommandType\x12\x10\n\x0cUNKNOWN_TYPE\x10\x00\x12\x1f\n\x1b\x43HECK_FUZZER_BINDER_SERVICE\x10\x01\x12\x1f\n\x1bSTART_FUZZER_BINDER_SERVICE\x10\x02\x12\x0c\n\x08GET_HALS\x10\x65\x12\x0e\n\nSELECT_HAL\x10\x66\x12\x12\n\rGET_FUNCTIONS\x10\xc9\x01\x12\x12\n\rCALL_FUNCTION\x10\xca\x01*7\n\x0cResponseCode\x12\x10\n\x0cUNKNOWN_CODE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02')

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='android.vts.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_TYPE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECK_FUZZER_BINDER_SERVICE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_FUZZER_BINDER_SERVICE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_HALS', index=3, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECT_HAL', index=4, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_FUNCTIONS', index=5, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL_FUNCTION', index=6, number=202,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=265,
  serialized_end=432,
)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
_RESPONSECODE = _descriptor.EnumDescriptor(
  name='ResponseCode',
  full_name='android.vts.ResponseCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=434,
  serialized_end=489,
)

ResponseCode = enum_type_wrapper.EnumTypeWrapper(_RESPONSECODE)
UNKNOWN_TYPE = 0
CHECK_FUZZER_BINDER_SERVICE = 1
START_FUZZER_BINDER_SERVICE = 2
GET_HALS = 101
SELECT_HAL = 102
GET_FUNCTIONS = 201
CALL_FUNCTION = 202
UNKNOWN_CODE = 0
SUCCESS = 1
FAIL = 2



_ANDROIDSYSTEMCONTROLCOMMANDMESSAGE = _descriptor.Descriptor(
  name='AndroidSystemControlCommandMessage',
  full_name='android.vts.AndroidSystemControlCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_type', full_name='android.vts.AndroidSystemControlCommandMessage.command_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_name', full_name='android.vts.AndroidSystemControlCommandMessage.target_name', index=1,
      number=1001, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=156,
)


_ANDROIDSYSTEMCONTROLRESPONSEMESSAGE = _descriptor.Descriptor(
  name='AndroidSystemControlResponseMessage',
  full_name='android.vts.AndroidSystemControlResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_code', full_name='android.vts.AndroidSystemControlResponseMessage.response_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reason', full_name='android.vts.AndroidSystemControlResponseMessage.reason', index=1,
      number=1001, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=158,
  serialized_end=262,
)

_ANDROIDSYSTEMCONTROLCOMMANDMESSAGE.fields_by_name['command_type'].enum_type = _COMMANDTYPE
_ANDROIDSYSTEMCONTROLRESPONSEMESSAGE.fields_by_name['response_code'].enum_type = _RESPONSECODE
DESCRIPTOR.message_types_by_name['AndroidSystemControlCommandMessage'] = _ANDROIDSYSTEMCONTROLCOMMANDMESSAGE
DESCRIPTOR.message_types_by_name['AndroidSystemControlResponseMessage'] = _ANDROIDSYSTEMCONTROLRESPONSEMESSAGE

class AndroidSystemControlCommandMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANDROIDSYSTEMCONTROLCOMMANDMESSAGE

  # @@protoc_insertion_point(class_scope:android.vts.AndroidSystemControlCommandMessage)

class AndroidSystemControlResponseMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANDROIDSYSTEMCONTROLRESPONSEMESSAGE

  # @@protoc_insertion_point(class_scope:android.vts.AndroidSystemControlResponseMessage)


# @@protoc_insertion_point(module_scope)
