# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VtsDriverControlMessage.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VtsDriverControlMessage.proto',
  package='android.vts',
  serialized_pb='\n\x1dVtsDriverControlMessage.proto\x12\x0b\x61ndroid.vts\"\x85\x02\n\x1eVtsDriverControlCommandMessage\x12\x37\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32!.android.vts.VtsDriverCommandType\x12\x14\n\x0bstatus_type\x18\xcd\x08 \x01(\x05\x12\x12\n\tfile_path\x18\xb1\t \x01(\x0c\x12\x15\n\x0ctarget_class\x18\xb2\t \x01(\x05\x12\x14\n\x0btarget_type\x18\xb3\t \x01(\x05\x12\x17\n\x0etarget_version\x18\xb4\t \x01(\x02\x12\x14\n\x0bmodule_name\x18\xb5\t \x01(\x0c\x12\x0c\n\x03\x61rg\x18\xf9\n \x01(\x0c\x12\x16\n\rshell_command\x18\xd1\x0f \x03(\x0c\"\xc0\x01\n\x1fVtsDriverControlResponseMessage\x12\x39\n\rresponse_code\x18\x01 \x01(\x0e\x32\".android.vts.VtsDriverResponseCode\x12\x14\n\x0creturn_value\x18\x0b \x01(\x05\x12\x16\n\x0ereturn_message\x18\x0c \x01(\x0c\x12\x0f\n\x06stdout\x18\xe9\x07 \x03(\x0c\x12\x0f\n\x06stderr\x18\xea\x07 \x03(\x0c\x12\x12\n\texit_code\x18\xeb\x07 \x03(\x05*\xb5\x01\n\x14VtsDriverCommandType\x12#\n\x1fUNKNOWN_VTS_DRIVER_COMMAND_TYPE\x10\x00\x12\x08\n\x04\x45XIT\x10\x01\x12\x0e\n\nGET_STATUS\x10\x02\x12\x0c\n\x08LOAD_HAL\x10\x65\x12\x12\n\x0eLIST_FUNCTIONS\x10\x66\x12\x11\n\rCALL_FUNCTION\x10g\x12\x14\n\x0f\x45XECUTE_COMMAND\x10\xc9\x01\x12\x13\n\x0eINVOKE_SYSCALL\x10\xca\x01*|\n\x15VtsDriverResponseCode\x12$\n UNKNOWN_VTS_DRIVER_RESPONSE_CODE\x10\x00\x12\x1f\n\x1bVTS_DRIVER_RESPONSE_SUCCESS\x10\x01\x12\x1c\n\x18VTS_DRIVER_RESPONSE_FAIL\x10\x02')

_VTSDRIVERCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='VtsDriverCommandType',
  full_name='android.vts.VtsDriverCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_VTS_DRIVER_COMMAND_TYPE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_STATUS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD_HAL', index=3, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIST_FUNCTIONS', index=4, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CALL_FUNCTION', index=5, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXECUTE_COMMAND', index=6, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVOKE_SYSCALL', index=7, number=202,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=506,
  serialized_end=687,
)

VtsDriverCommandType = enum_type_wrapper.EnumTypeWrapper(_VTSDRIVERCOMMANDTYPE)
_VTSDRIVERRESPONSECODE = _descriptor.EnumDescriptor(
  name='VtsDriverResponseCode',
  full_name='android.vts.VtsDriverResponseCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_VTS_DRIVER_RESPONSE_CODE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VTS_DRIVER_RESPONSE_SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VTS_DRIVER_RESPONSE_FAIL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=689,
  serialized_end=813,
)

VtsDriverResponseCode = enum_type_wrapper.EnumTypeWrapper(_VTSDRIVERRESPONSECODE)
UNKNOWN_VTS_DRIVER_COMMAND_TYPE = 0
EXIT = 1
GET_STATUS = 2
LOAD_HAL = 101
LIST_FUNCTIONS = 102
CALL_FUNCTION = 103
EXECUTE_COMMAND = 201
INVOKE_SYSCALL = 202
UNKNOWN_VTS_DRIVER_RESPONSE_CODE = 0
VTS_DRIVER_RESPONSE_SUCCESS = 1
VTS_DRIVER_RESPONSE_FAIL = 2



_VTSDRIVERCONTROLCOMMANDMESSAGE = _descriptor.Descriptor(
  name='VtsDriverControlCommandMessage',
  full_name='android.vts.VtsDriverControlCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_type', full_name='android.vts.VtsDriverControlCommandMessage.command_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_type', full_name='android.vts.VtsDriverControlCommandMessage.status_type', index=1,
      number=1101, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='android.vts.VtsDriverControlCommandMessage.file_path', index=2,
      number=1201, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_class', full_name='android.vts.VtsDriverControlCommandMessage.target_class', index=3,
      number=1202, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_type', full_name='android.vts.VtsDriverControlCommandMessage.target_type', index=4,
      number=1203, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_version', full_name='android.vts.VtsDriverControlCommandMessage.target_version', index=5,
      number=1204, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='module_name', full_name='android.vts.VtsDriverControlCommandMessage.module_name', index=6,
      number=1205, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arg', full_name='android.vts.VtsDriverControlCommandMessage.arg', index=7,
      number=1401, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shell_command', full_name='android.vts.VtsDriverControlCommandMessage.shell_command', index=8,
      number=2001, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=308,
)


_VTSDRIVERCONTROLRESPONSEMESSAGE = _descriptor.Descriptor(
  name='VtsDriverControlResponseMessage',
  full_name='android.vts.VtsDriverControlResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_code', full_name='android.vts.VtsDriverControlResponseMessage.response_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='return_value', full_name='android.vts.VtsDriverControlResponseMessage.return_value', index=1,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='return_message', full_name='android.vts.VtsDriverControlResponseMessage.return_message', index=2,
      number=12, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='android.vts.VtsDriverControlResponseMessage.stdout', index=3,
      number=1001, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='android.vts.VtsDriverControlResponseMessage.stderr', index=4,
      number=1002, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='android.vts.VtsDriverControlResponseMessage.exit_code', index=5,
      number=1003, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=311,
  serialized_end=503,
)

_VTSDRIVERCONTROLCOMMANDMESSAGE.fields_by_name['command_type'].enum_type = _VTSDRIVERCOMMANDTYPE
_VTSDRIVERCONTROLRESPONSEMESSAGE.fields_by_name['response_code'].enum_type = _VTSDRIVERRESPONSECODE
DESCRIPTOR.message_types_by_name['VtsDriverControlCommandMessage'] = _VTSDRIVERCONTROLCOMMANDMESSAGE
DESCRIPTOR.message_types_by_name['VtsDriverControlResponseMessage'] = _VTSDRIVERCONTROLRESPONSEMESSAGE

class VtsDriverControlCommandMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VTSDRIVERCONTROLCOMMANDMESSAGE

  # @@protoc_insertion_point(class_scope:android.vts.VtsDriverControlCommandMessage)

class VtsDriverControlResponseMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VTSDRIVERCONTROLRESPONSEMESSAGE

  # @@protoc_insertion_point(class_scope:android.vts.VtsDriverControlResponseMessage)


# @@protoc_insertion_point(module_scope)
