// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VtsWebStatusMessage.proto

package com.google.android.vts.proto;

public final class VtsWebStatusMessage {
  private VtsWebStatusMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code android.vts.TestStatus}
   *
   * <pre>
   * To specify test case execution result.
   * </pre>
   */
  public enum TestStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEST_UNKNOWN = 0;</code>
     */
    TEST_UNKNOWN(0, 0),
    /**
     * <code>TEST_OK = 1;</code>
     */
    TEST_OK(1, 1),
    /**
     * <code>TEST_FAIL = 2;</code>
     */
    TEST_FAIL(2, 2),
    ;

    /**
     * <code>TEST_UNKNOWN = 0;</code>
     */
    public static final int TEST_UNKNOWN_VALUE = 0;
    /**
     * <code>TEST_OK = 1;</code>
     */
    public static final int TEST_OK_VALUE = 1;
    /**
     * <code>TEST_FAIL = 2;</code>
     */
    public static final int TEST_FAIL_VALUE = 2;


    public final int getNumber() { return value; }

    public static TestStatus valueOf(int value) {
      switch (value) {
        case 0: return TEST_UNKNOWN;
        case 1: return TEST_OK;
        case 2: return TEST_FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TestStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TestStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TestStatus>() {
            public TestStatus findValueByNumber(int number) {
              return TestStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.android.vts.proto.VtsWebStatusMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final TestStatus[] VALUES = values();

    public static TestStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TestStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:android.vts.TestStatus)
  }

  public interface TestStatusMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes test_suite = 1;
    /**
     * <code>optional bytes test_suite = 1;</code>
     *
     * <pre>
     * the test suite name.
     * </pre>
     */
    boolean hasTestSuite();
    /**
     * <code>optional bytes test_suite = 1;</code>
     *
     * <pre>
     * the test suite name.
     * </pre>
     */
    com.google.protobuf.ByteString getTestSuite();

    // optional bytes test = 2;
    /**
     * <code>optional bytes test = 2;</code>
     *
     * <pre>
     * the test name.
     * </pre>
     */
    boolean hasTest();
    /**
     * <code>optional bytes test = 2;</code>
     *
     * <pre>
     * the test name.
     * </pre>
     */
    com.google.protobuf.ByteString getTest();

    // optional int64 status_timestamp = 3;
    /**
     * <code>optional int64 status_timestamp = 3;</code>
     *
     * <pre>
     * status update timestamp.
     * </pre>
     */
    boolean hasStatusTimestamp();
    /**
     * <code>optional int64 status_timestamp = 3;</code>
     *
     * <pre>
     * status update timestamp.
     * </pre>
     */
    long getStatusTimestamp();

    // optional .android.vts.TestStatus status = 4;
    /**
     * <code>optional .android.vts.TestStatus status = 4;</code>
     *
     * <pre>
     * test status.
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional .android.vts.TestStatus status = 4;</code>
     *
     * <pre>
     * test status.
     * </pre>
     */
    com.google.android.vts.proto.VtsWebStatusMessage.TestStatus getStatus();

    // repeated bytes failed_testcases = 5;
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    java.util.List<com.google.protobuf.ByteString> getFailedTestcasesList();
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    int getFailedTestcasesCount();
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    com.google.protobuf.ByteString getFailedTestcases(int index);
  }
  /**
   * Protobuf type {@code android.vts.TestStatusMessage}
   *
   * <pre>
   * To specify a test execution report.
   * </pre>
   */
  public static final class TestStatusMessage extends
      com.google.protobuf.GeneratedMessage
      implements TestStatusMessageOrBuilder {
    // Use TestStatusMessage.newBuilder() to construct.
    private TestStatusMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TestStatusMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TestStatusMessage defaultInstance;
    public static TestStatusMessage getDefaultInstance() {
      return defaultInstance;
    }

    public TestStatusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TestStatusMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              testSuite_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              test_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              statusTimestamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.google.android.vts.proto.VtsWebStatusMessage.TestStatus value = com.google.android.vts.proto.VtsWebStatusMessage.TestStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                status_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                failedTestcases_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              failedTestcases_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          failedTestcases_ = java.util.Collections.unmodifiableList(failedTestcases_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.android.vts.proto.VtsWebStatusMessage.internal_static_android_vts_TestStatusMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.android.vts.proto.VtsWebStatusMessage.internal_static_android_vts_TestStatusMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.class, com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<TestStatusMessage> PARSER =
        new com.google.protobuf.AbstractParser<TestStatusMessage>() {
      public TestStatusMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestStatusMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TestStatusMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes test_suite = 1;
    public static final int TEST_SUITE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString testSuite_;
    /**
     * <code>optional bytes test_suite = 1;</code>
     *
     * <pre>
     * the test suite name.
     * </pre>
     */
    public boolean hasTestSuite() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes test_suite = 1;</code>
     *
     * <pre>
     * the test suite name.
     * </pre>
     */
    public com.google.protobuf.ByteString getTestSuite() {
      return testSuite_;
    }

    // optional bytes test = 2;
    public static final int TEST_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString test_;
    /**
     * <code>optional bytes test = 2;</code>
     *
     * <pre>
     * the test name.
     * </pre>
     */
    public boolean hasTest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes test = 2;</code>
     *
     * <pre>
     * the test name.
     * </pre>
     */
    public com.google.protobuf.ByteString getTest() {
      return test_;
    }

    // optional int64 status_timestamp = 3;
    public static final int STATUS_TIMESTAMP_FIELD_NUMBER = 3;
    private long statusTimestamp_;
    /**
     * <code>optional int64 status_timestamp = 3;</code>
     *
     * <pre>
     * status update timestamp.
     * </pre>
     */
    public boolean hasStatusTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 status_timestamp = 3;</code>
     *
     * <pre>
     * status update timestamp.
     * </pre>
     */
    public long getStatusTimestamp() {
      return statusTimestamp_;
    }

    // optional .android.vts.TestStatus status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private com.google.android.vts.proto.VtsWebStatusMessage.TestStatus status_;
    /**
     * <code>optional .android.vts.TestStatus status = 4;</code>
     *
     * <pre>
     * test status.
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .android.vts.TestStatus status = 4;</code>
     *
     * <pre>
     * test status.
     * </pre>
     */
    public com.google.android.vts.proto.VtsWebStatusMessage.TestStatus getStatus() {
      return status_;
    }

    // repeated bytes failed_testcases = 5;
    public static final int FAILED_TESTCASES_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> failedTestcases_;
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getFailedTestcasesList() {
      return failedTestcases_;
    }
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    public int getFailedTestcasesCount() {
      return failedTestcases_.size();
    }
    /**
     * <code>repeated bytes failed_testcases = 5;</code>
     *
     * <pre>
     * failed tests
     * </pre>
     */
    public com.google.protobuf.ByteString getFailedTestcases(int index) {
      return failedTestcases_.get(index);
    }

    private void initFields() {
      testSuite_ = com.google.protobuf.ByteString.EMPTY;
      test_ = com.google.protobuf.ByteString.EMPTY;
      statusTimestamp_ = 0L;
      status_ = com.google.android.vts.proto.VtsWebStatusMessage.TestStatus.TEST_UNKNOWN;
      failedTestcases_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, testSuite_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, test_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, statusTimestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, status_.getNumber());
      }
      for (int i = 0; i < failedTestcases_.size(); i++) {
        output.writeBytes(5, failedTestcases_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, testSuite_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, test_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, statusTimestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, status_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < failedTestcases_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(failedTestcases_.get(i));
        }
        size += dataSize;
        size += 1 * getFailedTestcasesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code android.vts.TestStatusMessage}
     *
     * <pre>
     * To specify a test execution report.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.android.vts.proto.VtsWebStatusMessage.internal_static_android_vts_TestStatusMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.android.vts.proto.VtsWebStatusMessage.internal_static_android_vts_TestStatusMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.class, com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.Builder.class);
      }

      // Construct using com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        testSuite_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        test_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        statusTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = com.google.android.vts.proto.VtsWebStatusMessage.TestStatus.TEST_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000008);
        failedTestcases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.android.vts.proto.VtsWebStatusMessage.internal_static_android_vts_TestStatusMessage_descriptor;
      }

      public com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage getDefaultInstanceForType() {
        return com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.getDefaultInstance();
      }

      public com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage build() {
        com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage buildPartial() {
        com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage result = new com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testSuite_ = testSuite_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.test_ = test_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.statusTimestamp_ = statusTimestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          failedTestcases_ = java.util.Collections.unmodifiableList(failedTestcases_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.failedTestcases_ = failedTestcases_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage) {
          return mergeFrom((com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage other) {
        if (other == com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage.getDefaultInstance()) return this;
        if (other.hasTestSuite()) {
          setTestSuite(other.getTestSuite());
        }
        if (other.hasTest()) {
          setTest(other.getTest());
        }
        if (other.hasStatusTimestamp()) {
          setStatusTimestamp(other.getStatusTimestamp());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (!other.failedTestcases_.isEmpty()) {
          if (failedTestcases_.isEmpty()) {
            failedTestcases_ = other.failedTestcases_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureFailedTestcasesIsMutable();
            failedTestcases_.addAll(other.failedTestcases_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.android.vts.proto.VtsWebStatusMessage.TestStatusMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes test_suite = 1;
      private com.google.protobuf.ByteString testSuite_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes test_suite = 1;</code>
       *
       * <pre>
       * the test suite name.
       * </pre>
       */
      public boolean hasTestSuite() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes test_suite = 1;</code>
       *
       * <pre>
       * the test suite name.
       * </pre>
       */
      public com.google.protobuf.ByteString getTestSuite() {
        return testSuite_;
      }
      /**
       * <code>optional bytes test_suite = 1;</code>
       *
       * <pre>
       * the test suite name.
       * </pre>
       */
      public Builder setTestSuite(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        testSuite_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes test_suite = 1;</code>
       *
       * <pre>
       * the test suite name.
       * </pre>
       */
      public Builder clearTestSuite() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testSuite_ = getDefaultInstance().getTestSuite();
        onChanged();
        return this;
      }

      // optional bytes test = 2;
      private com.google.protobuf.ByteString test_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes test = 2;</code>
       *
       * <pre>
       * the test name.
       * </pre>
       */
      public boolean hasTest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes test = 2;</code>
       *
       * <pre>
       * the test name.
       * </pre>
       */
      public com.google.protobuf.ByteString getTest() {
        return test_;
      }
      /**
       * <code>optional bytes test = 2;</code>
       *
       * <pre>
       * the test name.
       * </pre>
       */
      public Builder setTest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes test = 2;</code>
       *
       * <pre>
       * the test name.
       * </pre>
       */
      public Builder clearTest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        test_ = getDefaultInstance().getTest();
        onChanged();
        return this;
      }

      // optional int64 status_timestamp = 3;
      private long statusTimestamp_ ;
      /**
       * <code>optional int64 status_timestamp = 3;</code>
       *
       * <pre>
       * status update timestamp.
       * </pre>
       */
      public boolean hasStatusTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 status_timestamp = 3;</code>
       *
       * <pre>
       * status update timestamp.
       * </pre>
       */
      public long getStatusTimestamp() {
        return statusTimestamp_;
      }
      /**
       * <code>optional int64 status_timestamp = 3;</code>
       *
       * <pre>
       * status update timestamp.
       * </pre>
       */
      public Builder setStatusTimestamp(long value) {
        bitField0_ |= 0x00000004;
        statusTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 status_timestamp = 3;</code>
       *
       * <pre>
       * status update timestamp.
       * </pre>
       */
      public Builder clearStatusTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        statusTimestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .android.vts.TestStatus status = 4;
      private com.google.android.vts.proto.VtsWebStatusMessage.TestStatus status_ = com.google.android.vts.proto.VtsWebStatusMessage.TestStatus.TEST_UNKNOWN;
      /**
       * <code>optional .android.vts.TestStatus status = 4;</code>
       *
       * <pre>
       * test status.
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .android.vts.TestStatus status = 4;</code>
       *
       * <pre>
       * test status.
       * </pre>
       */
      public com.google.android.vts.proto.VtsWebStatusMessage.TestStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .android.vts.TestStatus status = 4;</code>
       *
       * <pre>
       * test status.
       * </pre>
       */
      public Builder setStatus(com.google.android.vts.proto.VtsWebStatusMessage.TestStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .android.vts.TestStatus status = 4;</code>
       *
       * <pre>
       * test status.
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        status_ = com.google.android.vts.proto.VtsWebStatusMessage.TestStatus.TEST_UNKNOWN;
        onChanged();
        return this;
      }

      // repeated bytes failed_testcases = 5;
      private java.util.List<com.google.protobuf.ByteString> failedTestcases_ = java.util.Collections.emptyList();
      private void ensureFailedTestcasesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          failedTestcases_ = new java.util.ArrayList<com.google.protobuf.ByteString>(failedTestcases_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getFailedTestcasesList() {
        return java.util.Collections.unmodifiableList(failedTestcases_);
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public int getFailedTestcasesCount() {
        return failedTestcases_.size();
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public com.google.protobuf.ByteString getFailedTestcases(int index) {
        return failedTestcases_.get(index);
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public Builder setFailedTestcases(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFailedTestcasesIsMutable();
        failedTestcases_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public Builder addFailedTestcases(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFailedTestcasesIsMutable();
        failedTestcases_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public Builder addAllFailedTestcases(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFailedTestcasesIsMutable();
        super.addAll(values, failedTestcases_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes failed_testcases = 5;</code>
       *
       * <pre>
       * failed tests
       * </pre>
       */
      public Builder clearFailedTestcases() {
        failedTestcases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:android.vts.TestStatusMessage)
    }

    static {
      defaultInstance = new TestStatusMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:android.vts.TestStatusMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_android_vts_TestStatusMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_android_vts_TestStatusMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031VtsWebStatusMessage.proto\022\013android.vts" +
      "\"\222\001\n\021TestStatusMessage\022\022\n\ntest_suite\030\001 \001" +
      "(\014\022\014\n\004test\030\002 \001(\014\022\030\n\020status_timestamp\030\003 \001" +
      "(\003\022\'\n\006status\030\004 \001(\0162\027.android.vts.TestSta" +
      "tus\022\030\n\020failed_testcases\030\005 \003(\014*:\n\nTestSta" +
      "tus\022\020\n\014TEST_UNKNOWN\020\000\022\013\n\007TEST_OK\020\001\022\r\n\tTE" +
      "ST_FAIL\020\002B3\n\034com.google.android.vts.prot" +
      "oB\023VtsWebStatusMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_android_vts_TestStatusMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_android_vts_TestStatusMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_android_vts_TestStatusMessage_descriptor,
              new java.lang.String[] { "TestSuite", "Test", "StatusTimestamp", "Status", "FailedTestcases", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
